import React from 'react'
import NavBar from './navBar'
import Head from 'next/head';
// import Footer from './Footer'
// import "../../styles/Layout.module.css"


const Layout = ({children}:any) => {
  return (
    <>
    <Head>
    <title>ZARA</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  
    <div >

      <NavBar/>
      <div>{children}</div>
      
    </div>
  
    </>
  )
}

export default Layout